### ISSUE TITLE
API to return one record at a time?

### ISSUE THREAD

**Issue by chinchani** [toravir/csd#2]
https://github.com/toravir/csd/blob/c3bcea2d6785de695aaf0209b570d689ab42c91d/libs/decoder.go#L502

Looking for an API that reads one CBOR record from a stream (performing needed sanity checks)

**Comment by toravir** [comment]
Sure that can be done - just curious how/where would you use this as opposed to manyObjects API that decodes all bytes in the stream ?

**Comment by chinchani** [comment]
I have some "reader" interface that implements Next() and expects one record at a time. Not uncommon for log crunchers.

**Comment by toravir** [comment]
Can you point me to some examples of such components ?? I am trying to decide if the the new API should write to the dst io.Writer interface like the current manyObjects api or instead return a JSON string or MAP Object (since the caller is likely doing more processing with the return value)..

**Comment by chinchani** [comment]
The API should ideally return a map object, which can be further converted at user's discretion.

**Comment by toravir** [comment]
I guess you are looking for unmarshal() from cbor bytes. You can look at https://github.com/2tvenom/cbor - it provides unmarshal() very similar to json.unmarshal().

**Comment by chinchani** [comment]
Can your API be aligned with this?
https://golang.org/src/encoding/json/stream.go

Looks like all moving parts are already present?

**Comment by toravir** [comment]
i understand your usecase now. Will provide a suitable API.
